### PR TITLE
Fixed CSS Issues Regarding Directions Feature

### LINKED ISSUE #127: [BUG] UI for building directions search has no css
**Describe the bug**
When searching for a building on the Building Directions screen, the search results are tiny and blend in with the background.

**To Reproduce**
1. Open the app.
2. Click on the building direction button.
3. Click on either search bar and start searching for a building.

**Expected behavior**
The items in the list should be easier to click on and have a background so that they are easy to read and don't blend in with the map.

**Screenshots**
Image

**Additional context**
No additional context required

### LINKED ISSUE #128: [BUG] Return button and route information overlap
**Describe the bug**
When the user picks a start and end destinations and the route is provided to them the router information (eta and distance) and the return button overlap.

**To Reproduce**
1. Open the app.
2. Press on the building direction button
3. Pick a start destination
4. Pick an end destination

**Expected behavior**
The button and the route information should not overlap

**Screenshots**
Image

**Additional context**
No other context required

### LINKED ISSUE #129: [BUG]  Building Popup shouldn't popup when searching for directions
**Describe the bug**
When a building is pressed on the building directions screen, the building pop up appears. This overlaps with the existing popup for selecting a start and end destinations.

**To Reproduce**
1. Open the app.
2. Press the Building Directions button.
3. Press on any building.
4. Press cancel on the 1st pop up

**Expected behavior**
The pop up should not be displayed

**Screenshots**
Image

**Additional context**
None required

### LINKED ISSUE #138: [BUG] Directions to campus button should be a toggle
**Describe the bug**
When the user clicks on the Direction to SGW or LOY campus's there should be a way to reset it, adding a toggle button would be the best course of action.

**To Reproduce**
1. Open the app.
2. Press on either LOY or SGW campus.
3. Press on Direction to LOY or SGW button.

**Expected behavior**
It should be a toggle button to allow the user to cancel the action of direction without needing to move to a different campus or screen.

**Screenshots**
The button is currently pressed
Image

**Additional context**
None required

### PR DESCRIPTION
**Pull request by Otterboi**
Fixed the following CSS and Bugs of the Directions Feature
1. Added CSS to the building search results and made the button to use current location more clear. 
closes #127 
2. Removed ability to see the building pop up when on the Building Directions screen. 
closes #129 
3. Fixed the CSS overlapping with the Return button and Route Information box. 
closes #128 
4. Added the ability to cancel directions between campuses but changing the functionality to a toggle button. 
closes #138 

### Change 1:
IMG_9715

### Change 2:
IMG_9718

### Change 3:
IMG_9716

### Change 4:
IMG_9720

### CODE REVIEW

File: Concordia_Campus_App/maps/MapScreen.js [hunk 1]
```diff
@@ -43,16 +43,17 @@ const MapScreen = ({route}) => {
   const [centerOnUserLocation, setCenterOnUserLocation] = useState(true);
   const [isUserLocationFetched, setIsUserLocationFetched] = useState(false);
   const [activeButton, setActiveButton] = useState('user');
+  const [activeCampusDirections, setActiveCampusDirectiosn] = useState(false);
```
Comment (anhtuann) [inline Concordia_Campus_App/maps/MapScreen.js:46]: typo mistake

**Comment by anhtuann** [comment]
Little nitpick but the "cancel directions" button is not centered between the first row and third row of buttons

File: Concordia_Campus_App/maps/MapScreen.js (hunk 1 above)
Comment (Otterboi) [reply Concordia_Campus_App/maps/MapScreen.js]: thanks for letting me know, completely missed this

**Comment by Otterboi** [comment]
> Little nitpick but the "cancel directions" button is not centered between the first row and third row of buttons, otherwise it's good!

I see what you mean, I've made these changes to get the button centered
IMG_9722

**Comment by Otterboi** [comment]
> > Little nitpick but the "cancel directions" button is not centered between the first row and third row of buttons, otherwise it's good!
> 
> I see what you mean, I've made these changes to get the button centered IMG_9722

I fixed other stuff as the buttons started moving when clicking on a different campus, but now the spacing looks a lot better in my opinion
IMG_9723

**Comment by anhtuann** [comment]
looks great now! good job
